parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: turismoplus
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: fdf3c3cb6187fe53349e9445828a2816d00d6580
    database_path: null
