#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        Richpolis\BackendBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: Richpolis\BackendBundle\Entity\Usuario, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/backend/login$
            security: false

        secured_area:
            pattern:    ^/backend
            form_login:
                check_path: backend_check
                login_path: backend_login
                default_target_path: backend_homepage
                always_use_default_target_path: true
            logout:
                path:   backend_logout
                target: backend_login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/users$, roles: ROLE_ADMIN }
        - { path: ^/backend, roles: ROLE_USER }