publicaciones:
    type:       annotation
    prefix:    /v1
    resource: Richpolis\PublicacionesBundle\Controller\PublicacionesController

galerias:
    type:       annotation
    prefix:     /v1
    resource: Richpolis\PublicacionesBundle\Controller\GaleriasController
