#categorias:
#    type:       rest
#    prefix:     /v1
#    name_prefix: api_1_
#    resource: Richpolis\PublicacionesBundle\Controller\CategoriasController

#publicaciones:
#    type:       rest
#    prefix:     /v1
#    name_prefix: api_1_
#    resource: Richpolis\PublicacionesBundle\Controller\PublicacionesController

#galerias:
#    type:       rest
#    prefix:     /v1
#    name_prefix: api_1_
#    resource: Richpolis\PublicacionesBundle\Controller\GaleriasController