<?php

namespace Richpolis\PaginasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaginaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaginaRepository extends EntityRepository
{
}
