<?php

namespace Richpolis\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AutobusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutobusRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
       
        $query=$em->createQuery('
            SELECT MAX(a.position) as value 
            FROM FrontendBundle:Autobus a 
            ORDER BY a.position ASC
        ');
        
        $max=$query->getResult();
        return $max[0]['value'];
    }
}
