<?php

namespace Richpolis\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExperienciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienciasRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
       
        $query=$em->createQuery('
            SELECT MAX(e.position) as value 
            FROM FrontendBundle:Experiencias e 
            ORDER BY e.position ASC
        ');
        
        $max=$query->getResult();
        return $max[0]['value'];
    }
    public function getExperienciasActivas(){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
               SELECT e 
               FROM FrontendBundle:Experiencias e 
               WHERE e.isActive = :active
               ORDER BY e.position ASC
        ')->setParameters(array('active'=>true));
        return $query->getResult();
    }
}
